apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-platform-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nine-4/devops-lab-gitops.git
    targetRevision: main
    path: argocd/applications

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
