apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-nonprod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nine-4/devops-lab-gitops.git
    targetRevision: main
    path: clusters/nonprod

  destination:
    name: devops-nonprod
    namespace: default
